### ISSUE TITLE
KeyError: 'plane_registration'

### ISSUE THREAD

**Issue by aaujon** [matteli/atlantic_server#1]
Hi,
I tried to use your app but i'm getting this error : 
Internal Server Error: /api/planes/G-ERT/cameras/
Traceback (most recent call last):
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/iloarnaud/.local/lib/python3.7/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/iloarnaud/git/atlantic_server/Atlantic/views.py", line 147, in get_queryset
    Camera.objects.filter(plane__registration=self.kwargs["plane_registration"])
KeyError: 'plane_registration'

Seems related to your last commit : 43db40d295f9c2b00386d91fbfab0ef81b250151, is there someting missing on UI side so plane_registraztion is send ?
Thanks !

**Comment by matteli** [comment]
Hi,
Did you install drf-nested-routers package and django-filter ?
Did you add a plane by the admin django page ?
I can't reproduce your bug.
There is no documentation for the moment and it's a job i need to do.
